pipeline {
    agent {
        label 'jenkins node'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Nelson-Fossi/DevOps_project.git'
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    // Adjust Docker commands for Windows
                    sh 'docker-compose build'
                }
            }
        }

        stage('Deploy to Local Docker Engine') {
            steps {
                script {
                    // Adjust Docker commands for Windows
                    sh 'docker-compose up -d'
                }
            }
        }
    }

    post {
        always {
            script {
                // Adjust Docker commands for Windows
                sh 'docker-compose down'
            }
        }
    }
}
